version: '3'

services:
    php:
        image: php:7.2-fpm-alpine
        working_dir: /scripts
        volumes:
            - ./:/scripts

    nginx:
        image: nginx:alpine
        volumes:
            - ./:/scripts
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
        ports:
            - 8888:80
